# Generated by Django 6.0.3 on 2026-04-18 16:38

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("display_name", models.CharField(default="", max_length=255)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("email_verified_at", models.DateTimeField(null=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date Joined"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Modified At"
                    ),
                ),
                ("last_active", models.DateTimeField(null=True)),
                ("last_login_time", models.DateTimeField(null=True)),
                ("last_login_ip", models.CharField(blank=True, max_length=255)),
                ("last_login_medium", models.CharField(default="email", max_length=20)),
                ("last_login_uagent", models.TextField(blank=True)),
                ("last_logout_time", models.DateTimeField(null=True)),
                ("last_logout_ip", models.CharField(blank=True, max_length=255)),
                ("masked_at", models.DateTimeField(null=True)),
            ],
            options={
                "verbose_name": "User",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=128)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("verification", "Verification"),
                            ("password_reset", "Password Reset"),
                            ("email_change", "Email Change"),
                            ("account_deletion", "Account Deletion"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Token",
                "db_table": "tokens",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "purpose"], name="tokens_user_id_b8df68_idx"
                    )
                ],
            },
        ),
    ]
